name: Build and Deploy Docs

on:
  workflow_dispatch:
  release:
    types:
      - released

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# We need contents: write to upload the documentation as a release asset.
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  DOCS_BUILD_DIR: docs

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qermit
        run: pip install .
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: If we're generating docs for unified doc site deployment, use a different conf.py
        if: ${{ github.event_name == 'release' }}
        run: cp docs_src/unified_docs_conf.py docs_src/conf.py
      - name: Build Docs
        run: |
          cd docs_src
          pip install -r requirements.txt
          ./build_docs.sh
          cd ../manual
          ./build_manual.sh
      - name: Save documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs_html
          path: ${{ env.DOCS_BUILD_DIR }}
      - name: Upload artifact
        if: ${{ github.event_name != 'release' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_BUILD_DIR }}
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name != 'release' }}
        id: deployment
        uses: actions/deploy-pages@v4
      - name: (on release) Zip up documentation to store as release asset
        if: ${{ github.event_name == 'release' }}
        run: |
          tar -cavf qermit-docs-${{ github.event.release.tag_name }}.tar.gz -C ${{ env.DOCS_BUILD_DIR }} .
      - name: (on release) Add documentation artifact as release asset
        if: ${{ github.event_name == 'release' }}
        run: gh release upload ${{ github.event.release.tag_name }} qermit-docs-${{ github.event.release.tag_name }}.tar.gz --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
